import { Trim } from "./trim"
import { Make } from "./make";

// export type Car = {
//     id: number,
//     name: string,
//     make_id: number,
//     price: number,
//     mileage: number,
//     image: string
//     make_name?: string,
//     trims?: Trim[],
//     selectedTrim?: string,
// }

// Generated by https://quicktype.io

export interface Car {
    id: number;
    make_model_id: number;
    year: number;
    name: string;
    description: string;
    image: string;
    mileage: number;
    price: number;
    msrp: number;
    invoice: number;
    created: Date;
    modified: Date;
    make_model: MakeModel;
    trims: Trim[];
    selectedTrim: string
    make_name: string;
    make_id: number;
    bodyType: string;
}

export interface MakeModel {
    id: number;
    make_id: number;
    name: string;
    make: Make;
}

// export interface Make {
//     id:   number;
//     name: string;
// }
