// Generated by https://quicktype.io

export interface Filter {
    bodiestype: string[];
    enginescylinders: number[];
    enginesdriveType: string[];
    enginesType: string[];
    enginestransmission: string[];
    enginesvalveTiming: string[];
    enginesvalves: number[];
}
